conformant = "Partial"
notes = """
Incorrectly reports error for type alias defined with ParamSpec.
Incorrectly rejects some valid type aliases when used in annotations.
Incorrectly evaluates generic type alias with ParamSpec with missing type argument.
Does not report invalid specialization of generic type aliases.
Does not report error for attempt to instantiate union type alias.
Does not report invalid specialization of already-specialized generic type alias.
"""
output = """
aliases_traditional.py:38:26 Incompatible parameter type [6]: In call `typing.GenericMeta.__getitem__`, for 1st positional argument, expected `Tuple[typing.Any, Type[Variable[$synthetic_attribute_resolution_variable]]]` but got `Tuple[object, TypeVar]`.
aliases_traditional.py:42:27 Incompatible parameter type [6]: In call `typing.GenericMeta.__getitem__`, for 1st positional argument, expected `Tuple[typing.Any, Type[Variable[$synthetic_attribute_resolution_variable]]]` but got `Tuple[ParamSpec, None]`.
aliases_traditional.py:54:8 Undefined or invalid type [11]: Annotation `GoodTypeAlias9` is not defined as a type.
aliases_traditional.py:58:9 Undefined or invalid type [11]: Annotation `GoodTypeAlias13` is not defined as a type.
aliases_traditional.py:62:25 Incompatible parameter type [6]: In call `typing.GenericMeta.__getitem__`, for 1st positional argument, expected `Type[Variable[_T]]` but got `UnionType`.
aliases_traditional.py:64:26 Incompatible parameter type [6]: In call `typing.GenericMeta.__getitem__`, for 1st positional argument, expected `Type[Variable[_T_co](covariant)]` but got `Tuple[Type[str], typing.Any]`.
aliases_traditional.py:65:26 Incompatible parameter type [6]: In call `typing.GenericMeta.__getitem__`, for 1st positional argument, expected `Type[Variable[_T_co](covariant)]` but got `Tuple[Type[int], Type[int], Type[int], Type[str]]`.
aliases_traditional.py:68:29 Incompatible parameter type [6]: In call `typing.GenericMeta.__getitem__`, for 1st positional argument, expected `Tuple[typing.Any, Type[Variable[$synthetic_attribute_resolution_variable]]]` but got `Tuple[List[Type[Union[int, str]]], None]`.
aliases_traditional.py:72:30 Incompatible parameter type [6]: In call `typing.GenericMeta.__getitem__`, for 1st positional argument, expected `Tuple[typing.Any, Type[Variable[$synthetic_attribute_resolution_variable]]]` but got `Tuple[typing.Any, None]`.
aliases_traditional.py:106:8 Undefined or invalid type [11]: Annotation `BadTypeAlias1` is not defined as a type.
aliases_traditional.py:107:8 Undefined or invalid type [11]: Annotation `BadTypeAlias2` is not defined as a type.
aliases_traditional.py:108:8 Undefined or invalid type [11]: Annotation `BadTypeAlias3` is not defined as a type.
aliases_traditional.py:109:8 Undefined or invalid type [11]: Annotation `BadTypeAlias4` is not defined as a type.
aliases_traditional.py:110:8 Undefined or invalid type [11]: Annotation `BadTypeAlias5` is not defined as a type.
aliases_traditional.py:111:8 Undefined or invalid type [11]: Annotation `BadTypeAlias6` is not defined as a type.
aliases_traditional.py:112:8 Undefined or invalid type [11]: Annotation `BadTypeAlias7` is not defined as a type.
aliases_traditional.py:113:8 Undefined or invalid type [11]: Annotation `BadTypeAlias8` is not defined as a type.
aliases_traditional.py:114:8 Undefined or invalid type [11]: Annotation `BadTypeAlias9` is not defined as a type.
aliases_traditional.py:115:9 Undefined or invalid type [11]: Annotation `BadTypeAlias10` is not defined as a type.
aliases_traditional.py:116:9 Undefined or invalid type [11]: Annotation `BadTypeAlias11` is not defined as a type.
aliases_traditional.py:117:9 Undefined or invalid type [11]: Annotation `BadTypeAlias12` is not defined as a type.
aliases_traditional.py:118:9 Undefined or invalid type [11]: Annotation `BadTypeAlias13` is not defined as a type.
aliases_traditional.py:119:9 Undefined or invalid type [11]: Annotation `BadTypeAlias14` is not defined as a type.
"""
