conformant = "Partial"
notes = """
Does not evaluate correct type for indexed named tuple instance with slice.
Does not report out-of-range index access with named tuple instance.
Does not reject named tuple element with no default value after one with a default.
Incorrectly rejects assignment of named tuple to a tuple with compatible type.
Does not reject attempt to use NamedTuple with multiple inheritance.
"""
output = """
namedtuples_define_class.py:29:27 Incompatible parameter type [6]: In call `typing.GenericMeta.__getitem__`, for 1st positional argument, expected `Type[Variable[_T_co](covariant)]` but got `Tuple[Type[int], Type[int]]`.
namedtuples_define_class.py:30:26 Incompatible parameter type [6]: In call `typing.GenericMeta.__getitem__`, for 1st positional argument, expected `Type[Variable[_T_co](covariant)]` but got `Tuple[Type[int], Type[int], Type[str]]`.
namedtuples_define_class.py:44:5 Missing argument [20]: Call `Point.__init__` expects argument `y`.
namedtuples_define_class.py:45:5 Missing argument [20]: Call `Point.__init__` expects argument `y`.
namedtuples_define_class.py:46:14 Incompatible parameter type [6]: In call `Point.__init__`, for 2nd positional argument, expected `int` but got `str`.
namedtuples_define_class.py:47:17 Incompatible parameter type [6]: In call `Point.__init__`, for argument `units`, expected `str` but got `int`.
namedtuples_define_class.py:48:5 Too many arguments [19]: Call `Point.__init__` expects 3 positional arguments, 4 were provided.
namedtuples_define_class.py:49:6 Unexpected keyword [28]: Unexpected keyword argument `other` to call `Point.__init__`.
namedtuples_define_class.py:73:0 Incompatible variable type [9]: Unable to unpack `PointWithName`, expected a tuple.
namedtuples_define_class.py:79:4 Invalid assignment [41]: Cannot reassign final attribute `x`.
namedtuples_define_class.py:98:18 Incompatible parameter type [6]: In call `Property.__init__`, for 2nd positional argument, expected `str` but got `float`.
"""
