conformant = "Unsupported"
notes = """
Type parameter syntax not yet support.
"""
output = """
generics_variance_inference.py:15: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:15: error: Name "T1" is not defined  [name-defined]
generics_variance_inference.py:16: error: Name "T2" is not defined  [name-defined]
generics_variance_inference.py:19: error: Name "T3" is not defined  [name-defined]
generics_variance_inference.py:23: error: "ClassA" expects no type arguments, but 3 given  [type-arg]
generics_variance_inference.py:24: error: "ClassA" expects no type arguments, but 3 given  [type-arg]
generics_variance_inference.py:25: error: "ClassA" expects no type arguments, but 3 given  [type-arg]
generics_variance_inference.py:26: error: "ClassA" expects no type arguments, but 3 given  [type-arg]
generics_variance_inference.py:28: error: "ClassA" expects no type arguments, but 3 given  [type-arg]
generics_variance_inference.py:29: error: "ClassA" expects no type arguments, but 3 given  [type-arg]
generics_variance_inference.py:32: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:33: error: A function returning TypeVar should receive at least one argument containing the same TypeVar  [type-var]
generics_variance_inference.py:40: error: "ShouldBeCovariant1" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:40: error: The type "type[ShouldBeCovariant1]" is not generic and not indexable  [misc]
generics_variance_inference.py:41: error: "ShouldBeCovariant1" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:41: error: The type "type[ShouldBeCovariant1]" is not generic and not indexable  [misc]
generics_variance_inference.py:44: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:48: error: Cannot instantiate abstract class "ShouldBeCovariant2" with abstract attributes "__getitem__" and "__len__"  [abstract]
generics_variance_inference.py:48: error: Incompatible types in assignment (expression has type "ShouldBeCovariant2[int]", variable has type "ShouldBeCovariant2[float]")  [assignment]
generics_variance_inference.py:49: error: Cannot instantiate abstract class "ShouldBeCovariant2" with abstract attributes "__getitem__" and "__len__"  [abstract]
generics_variance_inference.py:49: error: Incompatible types in assignment (expression has type "ShouldBeCovariant2[float]", variable has type "ShouldBeCovariant2[int]")  [assignment]
generics_variance_inference.py:52: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:57: error: "ShouldBeCovariant3" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:57: error: The type "type[ShouldBeCovariant3]" is not generic and not indexable  [misc]
generics_variance_inference.py:58: error: "ShouldBeCovariant3" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:58: error: The type "type[ShouldBeCovariant3]" is not generic and not indexable  [misc]
generics_variance_inference.py:62: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:63: error: Type variable "generics_variance_inference.T" is unbound  [valid-type]
generics_variance_inference.py:63: note: (Hint: Use "Generic[T]" or "Protocol[T]" base class to bind "T" inside a class)
generics_variance_inference.py:63: note: (Hint: Use "T" in function signature to bind "T" inside a function)
generics_variance_inference.py:66: error: "ShouldBeCovariant4" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:66: error: The type "type[ShouldBeCovariant4]" is not generic and not indexable  [misc]
generics_variance_inference.py:67: error: "ShouldBeCovariant4" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:67: error: The type "type[ShouldBeCovariant4]" is not generic and not indexable  [misc]
generics_variance_inference.py:70: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:75: error: A function returning TypeVar should receive at least one argument containing the same TypeVar  [type-var]
generics_variance_inference.py:79: error: "ShouldBeCovariant5" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:79: error: The type "type[ShouldBeCovariant5]" is not generic and not indexable  [misc]
generics_variance_inference.py:80: error: "ShouldBeCovariant5" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:80: error: The type "type[ShouldBeCovariant5]" is not generic and not indexable  [misc]
generics_variance_inference.py:83: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:96: error: "ShouldBeInvariant1" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:96: error: The type "type[ShouldBeInvariant1]" is not generic and not indexable  [misc]
generics_variance_inference.py:97: error: "ShouldBeInvariant1" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:97: error: The type "type[ShouldBeInvariant1]" is not generic and not indexable  [misc]
generics_variance_inference.py:100: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:104: error: A function returning TypeVar should receive at least one argument containing the same TypeVar  [type-var]
generics_variance_inference.py:111: error: "ShouldBeInvariant2" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:111: error: The type "type[ShouldBeInvariant2]" is not generic and not indexable  [misc]
generics_variance_inference.py:112: error: "ShouldBeInvariant2" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:112: error: The type "type[ShouldBeInvariant2]" is not generic and not indexable  [misc]
generics_variance_inference.py:115: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:115: error: Name "K" is not defined  [name-defined]
generics_variance_inference.py:115: error: Name "V" is not defined  [name-defined]
generics_variance_inference.py:119: error: "ShouldBeInvariant3" expects no type arguments, but 2 given  [type-arg]
generics_variance_inference.py:119: error: The type "type[ShouldBeInvariant3]" is not generic and not indexable  [misc]
generics_variance_inference.py:120: error: "ShouldBeInvariant3" expects no type arguments, but 2 given  [type-arg]
generics_variance_inference.py:120: error: The type "type[ShouldBeInvariant3]" is not generic and not indexable  [misc]
generics_variance_inference.py:121: error: "ShouldBeInvariant3" expects no type arguments, but 2 given  [type-arg]
generics_variance_inference.py:121: error: The type "type[ShouldBeInvariant3]" is not generic and not indexable  [misc]
generics_variance_inference.py:122: error: "ShouldBeInvariant3" expects no type arguments, but 2 given  [type-arg]
generics_variance_inference.py:122: error: The type "type[ShouldBeInvariant3]" is not generic and not indexable  [misc]
generics_variance_inference.py:126: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:127: error: Type variable "generics_variance_inference.T" is unbound  [valid-type]
generics_variance_inference.py:127: note: (Hint: Use "Generic[T]" or "Protocol[T]" base class to bind "T" inside a class)
generics_variance_inference.py:127: note: (Hint: Use "T" in function signature to bind "T" inside a function)
generics_variance_inference.py:130: error: "ShouldBeInvariant4" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:130: error: The type "type[ShouldBeInvariant4]" is not generic and not indexable  [misc]
generics_variance_inference.py:133: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:138: error: "ShouldBeInvariant5" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:138: error: The type "type[ShouldBeInvariant5]" is not generic and not indexable  [misc]
generics_variance_inference.py:141: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:149: error: "ShouldBeContravariant1" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:149: error: The type "type[ShouldBeContravariant1]" is not generic and not indexable  [misc]
generics_variance_inference.py:150: error: "ShouldBeContravariant1" expects no type arguments, but 1 given  [type-arg]
generics_variance_inference.py:150: error: The type "type[ShouldBeContravariant1]" is not generic and not indexable  [misc]
generics_variance_inference.py:165: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:169: error: Incompatible types in assignment (expression has type "ShouldBeInvariant6[float]", variable has type "ShouldBeInvariant6[int]")  [assignment]
generics_variance_inference.py:170: error: Incompatible types in assignment (expression has type "ShouldBeInvariant6[int]", variable has type "ShouldBeInvariant6[float]")  [assignment]
generics_variance_inference.py:177: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:181: error: Incompatible types in assignment (expression has type "ShouldBeCovariant6[float]", variable has type "ShouldBeCovariant6[int]")  [assignment]
generics_variance_inference.py:182: error: Incompatible types in assignment (expression has type "ShouldBeCovariant6[int]", variable has type "ShouldBeCovariant6[float]")  [assignment]
generics_variance_inference.py:189: error: PEP 695 generics are not yet supported  [valid-type]
generics_variance_inference.py:193: error: Incompatible types in assignment (expression has type "ShouldBeContravariant2[float]", variable has type "ShouldBeContravariant2[int]")  [assignment]
generics_variance_inference.py:194: error: Incompatible types in assignment (expression has type "ShouldBeContravariant2[int]", variable has type "ShouldBeContravariant2[float]")  [assignment]
"""
conformance_automated = "Fail"
errors_diff = """
Line 15: Unexpected errors ['generics_variance_inference.py:15: error: PEP 695 generics are not yet supported  [valid-type]', 'generics_variance_inference.py:15: error: Name "T1" is not defined  [name-defined]']
Line 16: Unexpected errors ['generics_variance_inference.py:16: error: Name "T2" is not defined  [name-defined]']
Line 19: Unexpected errors ['generics_variance_inference.py:19: error: Name "T3" is not defined  [name-defined]']
Line 23: Unexpected errors ['generics_variance_inference.py:23: error: "ClassA" expects no type arguments, but 3 given  [type-arg]']
Line 26: Unexpected errors ['generics_variance_inference.py:26: error: "ClassA" expects no type arguments, but 3 given  [type-arg]']
Line 29: Unexpected errors ['generics_variance_inference.py:29: error: "ClassA" expects no type arguments, but 3 given  [type-arg]']
Line 32: Unexpected errors ['generics_variance_inference.py:32: error: PEP 695 generics are not yet supported  [valid-type]']
Line 33: Unexpected errors ['generics_variance_inference.py:33: error: A function returning TypeVar should receive at least one argument containing the same TypeVar  [type-var]']
Line 40: Unexpected errors ['generics_variance_inference.py:40: error: "ShouldBeCovariant1" expects no type arguments, but 1 given  [type-arg]', 'generics_variance_inference.py:40: error: The type "type[ShouldBeCovariant1]" is not generic and not indexable  [misc]']
Line 44: Unexpected errors ['generics_variance_inference.py:44: error: PEP 695 generics are not yet supported  [valid-type]']
Line 48: Unexpected errors ['generics_variance_inference.py:48: error: Cannot instantiate abstract class "ShouldBeCovariant2" with abstract attributes "__getitem__" and "__len__"  [abstract]', 'generics_variance_inference.py:48: error: Incompatible types in assignment (expression has type "ShouldBeCovariant2[int]", variable has type "ShouldBeCovariant2[float]")  [assignment]']
Line 52: Unexpected errors ['generics_variance_inference.py:52: error: PEP 695 generics are not yet supported  [valid-type]']
Line 57: Unexpected errors ['generics_variance_inference.py:57: error: "ShouldBeCovariant3" expects no type arguments, but 1 given  [type-arg]', 'generics_variance_inference.py:57: error: The type "type[ShouldBeCovariant3]" is not generic and not indexable  [misc]']
Line 62: Unexpected errors ['generics_variance_inference.py:62: error: PEP 695 generics are not yet supported  [valid-type]']
Line 63: Unexpected errors ['generics_variance_inference.py:63: error: Type variable "generics_variance_inference.T" is unbound  [valid-type]']
Line 66: Unexpected errors ['generics_variance_inference.py:66: error: "ShouldBeCovariant4" expects no type arguments, but 1 given  [type-arg]', 'generics_variance_inference.py:66: error: The type "type[ShouldBeCovariant4]" is not generic and not indexable  [misc]']
Line 70: Unexpected errors ['generics_variance_inference.py:70: error: PEP 695 generics are not yet supported  [valid-type]']
Line 75: Unexpected errors ['generics_variance_inference.py:75: error: A function returning TypeVar should receive at least one argument containing the same TypeVar  [type-var]']
Line 79: Unexpected errors ['generics_variance_inference.py:79: error: "ShouldBeCovariant5" expects no type arguments, but 1 given  [type-arg]', 'generics_variance_inference.py:79: error: The type "type[ShouldBeCovariant5]" is not generic and not indexable  [misc]']
Line 83: Unexpected errors ['generics_variance_inference.py:83: error: PEP 695 generics are not yet supported  [valid-type]']
Line 100: Unexpected errors ['generics_variance_inference.py:100: error: PEP 695 generics are not yet supported  [valid-type]']
Line 104: Unexpected errors ['generics_variance_inference.py:104: error: A function returning TypeVar should receive at least one argument containing the same TypeVar  [type-var]']
Line 115: Unexpected errors ['generics_variance_inference.py:115: error: PEP 695 generics are not yet supported  [valid-type]', 'generics_variance_inference.py:115: error: Name "K" is not defined  [name-defined]', 'generics_variance_inference.py:115: error: Name "V" is not defined  [name-defined]']
Line 126: Unexpected errors ['generics_variance_inference.py:126: error: PEP 695 generics are not yet supported  [valid-type]']
Line 127: Unexpected errors ['generics_variance_inference.py:127: error: Type variable "generics_variance_inference.T" is unbound  [valid-type]']
Line 133: Unexpected errors ['generics_variance_inference.py:133: error: PEP 695 generics are not yet supported  [valid-type]']
Line 141: Unexpected errors ['generics_variance_inference.py:141: error: PEP 695 generics are not yet supported  [valid-type]']
Line 150: Unexpected errors ['generics_variance_inference.py:150: error: "ShouldBeContravariant1" expects no type arguments, but 1 given  [type-arg]', 'generics_variance_inference.py:150: error: The type "type[ShouldBeContravariant1]" is not generic and not indexable  [misc]']
Line 165: Unexpected errors ['generics_variance_inference.py:165: error: PEP 695 generics are not yet supported  [valid-type]']
Line 177: Unexpected errors ['generics_variance_inference.py:177: error: PEP 695 generics are not yet supported  [valid-type]']
Line 182: Unexpected errors ['generics_variance_inference.py:182: error: Incompatible types in assignment (expression has type "ShouldBeCovariant6[int]", variable has type "ShouldBeCovariant6[float]")  [assignment]']
Line 189: Unexpected errors ['generics_variance_inference.py:189: error: PEP 695 generics are not yet supported  [valid-type]']
Line 193: Unexpected errors ['generics_variance_inference.py:193: error: Incompatible types in assignment (expression has type "ShouldBeContravariant2[float]", variable has type "ShouldBeContravariant2[int]")  [assignment]']
"""
