conformant = "Unsupported"
notes = """
Does not understand `Literal` type annotation.
"""
output = """
File "literals_semantics.py", line 10, in <module>: Type annotation for v2 does not match type of assignment [annotation-type-mismatch]
File "literals_semantics.py", line 12, in <module>: Invalid type annotation 'Literal'  [invalid-annotation]
File "literals_semantics.py", line 12, in <module>: Invalid type annotation 'L[-3]'  [invalid-annotation]
File "literals_semantics.py", line 16, in <module>: Invalid type annotation 'Literal'  [invalid-annotation]
File "literals_semantics.py", line 17, in func1: Invalid type annotation 'Literal[20]'  [invalid-annotation]
File "literals_semantics.py", line 18, in func1: Invalid type annotation 'Literal[20]'  [invalid-annotation]
File "literals_semantics.py", line 19, in func1: Invalid type annotation 'Literal[20]'  [invalid-annotation]
"""
conformance_automated = "Fail"
errors_diff = """
Line 24: Expected 1 errors
Line 25: Expected 1 errors
Line 33: Expected 1 errors
Line 12: Unexpected errors ['File "literals_semantics.py", line 12, in <module>: Invalid type annotation \\'Literal\\'  [invalid-annotation]', 'File "literals_semantics.py", line 12, in <module>: Invalid type annotation \\'L[-3]\\'  [invalid-annotation]']
Line 16: Unexpected errors ['File "literals_semantics.py", line 16, in <module>: Invalid type annotation \\'Literal\\'  [invalid-annotation]']
Line 17: Unexpected errors ['File "literals_semantics.py", line 17, in func1: Invalid type annotation \\'Literal[20]\\'  [invalid-annotation]']
Line 18: Unexpected errors ['File "literals_semantics.py", line 18, in func1: Invalid type annotation \\'Literal[20]\\'  [invalid-annotation]']
Line 19: Unexpected errors ['File "literals_semantics.py", line 19, in func1: Invalid type annotation \\'Literal[20]\\'  [invalid-annotation]']
"""
