conformant = "Partial"
notes = """
Reports errors for protocol static method with "..." implementation.
Does not report error when instance variable is set through "self" access in protocol class.
Does not report protocol mismatch when concrete class has attribute with covariant type and protocol attribute is mutable.
Does not reject ClassVar in concrete class when attribute in protocol is not ClassVar.
Does not reject read-only property in concrete class when attribute in protocol is mutable.
Does not reject covariant attribute type when protocol attribute is mutable.
Does not detect protocol mismatch if concrete method is missing annotations.
Does not detect protocol mismatch if concrete method's parameters are keyword-only.
Does not detect protocol mismatch if concrete method's parameters are position-only.
Does not detect protocol mismatch if concrete method is a classmethod.
Does not detect protocol mismatch if concrete method is a staticmethod.
Does not reject read-only property in concrete class when protocol has settable property.
Does not reject immutable named tuple attribute in concrete class when protocol attribute is mutable.
Does not reject immutable frozen dataclass attribute in concrete class when protocol attribute is mutable.
"""
output = """
File "protocols_definition.py", line 30, in <module>: Function close_all was called with the wrong arguments [wrong-arg-types]
File "protocols_definition.py", line 45, in third: bad return type [bad-return-type]
File "protocols_definition.py", line 114, in <module>: Type annotation for v2_bad1 does not match type of assignment [annotation-type-mismatch]
File "protocols_definition.py", line 115, in <module>: Type annotation for v2_bad2 does not match type of assignment [annotation-type-mismatch]
File "protocols_definition.py", line 156, in <module>: Type annotation for v3_bad1 does not match type of assignment [annotation-type-mismatch]
File "protocols_definition.py", line 159, in <module>: Type annotation for v3_bad4 does not match type of assignment [annotation-type-mismatch]
File "protocols_definition.py", line 218, in <module>: Type annotation for v4_bad1 does not match type of assignment [annotation-type-mismatch]
File "protocols_definition.py", line 219, in <module>: Type annotation for v4_bad2 does not match type of assignment [annotation-type-mismatch]
"""
conformance_automated = "Fail"
errors_diff = """
Line 67: Expected 1 errors
Line 116: Expected 1 errors
Line 117: Expected 1 errors
Line 157: Expected 1 errors
Line 158: Expected 1 errors
Line 160: Expected 1 errors
Line 285: Expected 1 errors
Line 286: Expected 1 errors
Line 287: Expected 1 errors
Line 288: Expected 1 errors
Line 289: Expected 1 errors
Line 339: Expected 1 errors
Line 340: Expected 1 errors
Line 341: Expected 1 errors
Line 45: Unexpected errors ['File "protocols_definition.py", line 45, in third: bad return type [bad-return-type]']
"""
